FROM python:3
ENV PYTHONUNBUFFERED 1
RUN mkdir /ms1
WORKDIR /ms1
ADD . /ms1/
COPY requirements.txt /ms1/
RUN python -m pip install -r requirements.txt
EXPOSE 8080
CMD python manage.py makemigrations && python manage.py migrate && python manage.py runserver 8000
